### ISSUE TITLE
Sitemap is not generating

### ISSUE THREAD

**Issue by annamisak** [annamisak/annamisak#13]
Sorry to bother you Thomas, but I am seemed to be having issues with the sitemap.xml. It won't generate the sitemap for my website. What am I doing wrong?

@thomasjbradley

**Comment by thomasjbradley** [comment]
There's one small bug, on this line:
https://github.com/annamisak/annamisak.com/blob/gh-pages/sitemap.xml#L8
It should be `post.layout` to make the `post` on the line above.

**Comment by annamisak** [comment]
Thank you! That solved the problem :)
