### ISSUE TITLE
Extra Space Above Nav Bar (Safari 9)

### ISSUE THREAD

**Issue by valeriebordeleau** [annamisak/annamisak#2]
![screen shot 2015-10-08 at 8 56 05 am](https://cloud.githubusercontent.com/assets/6373198/10366755/6f7e9588-6d9a-11e5-99ee-c8d70b512890.png)

There's an extra space above your nav, I'd double check the padding/margins

**Comment by benmarley** [comment]
the top nav is cutoff on windows 8
the portrait  image is cutoff in portrait
H1, H2, and p on banner all cram together
