### ISSUE TITLE
Firefox Testing  

### ISSUE THREAD

**Issue by paisley-laurenzio** [annamisak/annamisak#9]
One thing is that you might want to have your projects visible in the current work section because if you are just scrolling through you don't see anything and you want people to be able to see your work without digging. 

![screen shot 2015-10-08 at 9 28 24 am](https://cloud.githubusercontent.com/assets/6371044/10367511/f102389a-6d9e-11e5-92a2-461a1000ce0e.png)

I also noticed that your nav at the top isn't fixed to the top of the screen. you might want to look at that? Just a suggestion!

**Comment by kayleemenard** [comment]
I just finished testing in Firefox on my phone, and I ran into a similar issue in landscape format: 

![2015-10-08 13 31 48](https://cloud.githubusercontent.com/assets/6373202/10367723/0e285908-6da0-11e5-8e4e-c89f416d70cb.png)
(this is only a portion of the background colour space)

There's also empty space between the background colour and the edge of the browser.
